import { clearSearch, getContainer, setPage } from "./ui.js?v=44";
import { ROUTES } from "./config.js?v=116";
import { escapeHtml, normalizeText } from "./utils.js?v=44";
import { renderAccountingSandbox } from "./accounting-sandbox.js?v=1";

const SECTIONS = [
    ["dashboard", "Tableau de bord"], ["quotes", "Devis"], ["invoices", "Factures"], ["export", "Export comptable"], ["electronic", "Facturation électronique"], ["aids", "Aides financières"], ["settings", "Paramètres"]
];
const AID_TYPES = { cee: "CEE", maprimerenov: "MaPrimeRénov'", coup_de_pouce: "Prime Coup de Pouce", eco_ptz: "Éco-PTZ", regional: "Aide régionale", departmental: "Aide départementale", supplier: "Participation fournisseur", manufacturer: "Participation constructeur", custom: "Autre aide" };
let accounting = null;
let activeSection = "dashboard";

export async function renderAccounting(section = activeSection) {
    activeSection = SECTIONS.some(([id]) => id === section) ? section : "dashboard";
    clearSearch();
    setPage("Comptabilité & Facturation électronique", ROUTES.accounting, "detail");
    const container = getContainer();
    container.innerHTML = '<section class="client-panel accounting-shell"><p class="muted">Chargement du module comptable…</p></section>';
    const result = await api("/api/accounting");
    if (!result.ok) { container.innerHTML = `<section class="client-panel"><p class="auth-message error">${escapeHtml(result.message || "Impossible de charger le module comptable.")}</p></section>`; return; }
    accounting = result.data;
    const shell = container.querySelector(".accounting-shell");
    shell.innerHTML = `<header class="accounting-heading"><div><p class="eyebrow">Gestion financière</p><h2>Comptabilité & Facturation électronique</h2><p class="muted">Données isolées pour votre entreprise · exports, aides et transmissions PDP.</p></div><button type="button" class="secondary-button accounting-sandbox-launch" id="openAccountingSandbox">Ouvrir la Sandbox comptable</button></header><nav class="accounting-tabs" aria-label="Sections comptables">${SECTIONS.map(([id, label]) => `<button type="button" class="secondary-button${id === activeSection ? " active" : ""}" data-accounting-section="${id}">${label}</button>`).join("")}</nav><section id="accountingContent"></section>`;
    shell.querySelectorAll("[data-accounting-section]").forEach(button => button.addEventListener("click", () => renderAccounting(button.dataset.accountingSection)));
    shell.querySelector("#openAccountingSandbox").addEventListener("click", () => renderAccountingSandbox());
    const content = shell.querySelector("#accountingContent");
    ({ dashboard: renderDashboard, quotes: () => renderDocuments(content, "quote"), invoices: () => renderDocuments(content, "invoice"), export: renderExports, electronic: renderElectronic, aids: renderAids, settings: renderSettings })[activeSection](content);
}

function renderDashboard(node) {
    const data = accounting.dashboard;
    node.innerHTML = `<div class="accounting-cards"><article><span>Chiffre d’affaires</span><strong>${money(data.turnover)}</strong><small>${data.invoicesCount} facture(s)</small></article><article><span>Encaissements</span><strong>${money(data.collected)}</strong><small>Règlements saisis</small></article><article><span>À encaisser</span><strong>${money(data.outstanding)}</strong><small>${data.overdueCount} impayé(s)</small></article><article class="${data.overdueAmount ? "attention" : ""}"><span>Impayés</span><strong>${money(data.overdueAmount)}</strong><small>Échéances dépassées</small></article><article><span>Achats HT</span><strong>${money(data.purchasesHt)}</strong><small>Charges enregistrées</small></article></div><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Suivi des règlements</p><h3>Impayés et factures à encaisser</h3></div></div>${renderPaymentRows(accounting.documents.filter(item => item.documentType === "invoice" && item.paymentStatus !== "paid"))}</section>`;
}

function renderDocuments(node, type) {
    const label = type === "quote" ? "Devis" : "Factures";
    const documents = accounting.documents.filter(item => item.documentType === type);
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">${label}</p><h3>${type === "quote" ? "Devis, aides et reste à charge" : "Factures, règlements et impayés"}</h3></div><button type="button" class="secondary-button" id="accountingRefresh">Actualiser</button></div><input class="accounting-search" id="accountingDocumentSearch" type="search" placeholder="Rechercher un numéro ou un client"><div class="accounting-document-list" id="accountingDocumentList"></div></section>`;
    const list = node.querySelector("#accountingDocumentList");
    const render = () => {
        const query = normalizeText(node.querySelector("#accountingDocumentSearch").value);
        const shown = documents.filter(item => !query || normalizeText(`${item.documentNumber} ${item.customerName}`).includes(query));
        list.innerHTML = shown.length ? shown.map(item => `<article class="accounting-document"><div><p class="eyebrow">${escapeHtml(item.documentNumber)} · ${escapeHtml(item.status || "brouillon")}</p><h4>${escapeHtml(item.customerName)}</h4><small>${escapeHtml(date(item.issueDate))}${item.dueDate ? ` · Échéance ${escapeHtml(date(item.dueDate))}` : ""}</small></div><div class="accounting-document-totals"><strong>${money(item.totals.netPayable)}</strong><small>${type === "quote" ? `Aides ${money(item.totals.aids)} · TTC ${money(item.totals.ttc)}` : paymentLabel(item)}</small></div><div class="accounting-document-actions">${type === "quote" ? `<button type="button" class="secondary-button" data-financial="${item.id}">Aides / remises</button>` : `<button type="button" class="secondary-button" data-settlement="${item.id}" ${item.remainingAmount <= 0 ? "disabled" : ""}>Règlement</button><button type="button" class="secondary-button" data-credit="${item.id}">Créer un avoir</button>`}</div></article>`).join("") : '<p class="muted">Aucun document trouvé.</p>';
        list.querySelectorAll("[data-financial]").forEach(button => button.addEventListener("click", () => renderFinancialEditor(node, documents.find(item => String(item.id) === button.dataset.financial))));
        list.querySelectorAll("[data-settlement]").forEach(button => button.addEventListener("click", () => renderSettlementForm(node, documents.find(item => String(item.id) === button.dataset.settlement))));
        list.querySelectorAll("[data-credit]").forEach(button => button.addEventListener("click", () => createCredit(button.dataset.credit)));
    };
    node.querySelector("#accountingDocumentSearch").addEventListener("input", render);
    node.querySelector("#accountingRefresh").addEventListener("click", () => renderAccounting(activeSection));
    render();
}

function renderFinancialEditor(node, document) {
    const data = document.financialData || {};
    const autoAids = accounting.aids.filter(aid => aid.autoApply);
    node.insertAdjacentHTML("beforeend", `<section class="accounting-panel accounting-inline-form"><div class="form-heading"><div><p class="eyebrow">${escapeHtml(document.documentNumber)}</p><h3>Aides, remises et conditions</h3></div></div><form id="financialForm"><div class="form-grid"><label>Remise<select name="discountMode"><option value="fixed" ${data.discountMode === "fixed" ? "selected" : ""}>Montant fixe (€ HT)</option><option value="percentage" ${data.discountMode === "percentage" ? "selected" : ""}>Pourcentage (%)</option></select></label><label>Montant de la remise<input name="discountAmount" type="number" min="0" step="0.01" value="${escapeHtml(data.discountAmount || 0)}"></label><label>Acompte attendu<input name="depositAmount" type="number" min="0" step="0.01" value="${escapeHtml(data.depositAmount || 0)}"></label><label class="form-wide">Conditions particulières<textarea name="conditions" rows="2">${escapeHtml(data.conditions || "")}</textarea></label><label class="form-wide">Commentaires<textarea name="comments" rows="2">${escapeHtml(data.comments || "")}</textarea></label></div><fieldset class="accounting-aid-fieldset"><legend>Aides financières</legend>${accounting.aids.map(aid => `<label><input type="checkbox" name="aid" value="${aid.id}" ${(data.aids || []).some(item => item.name === aid.name) || aid.autoApply ? "checked" : ""}> ${escapeHtml(aid.name)} · ${aid.calculationMode === "percentage" ? `${aid.amount} %` : money(aid.amount)}</label>`).join("") || '<p class="muted">Créez d’abord vos aides dans l’onglet « Aides financières ».</p>'}</fieldset><p class="auth-message" id="financialMessage"></p><div class="calendar-form-actions"><button type="submit" class="secondary-button">Enregistrer les données financières</button><button type="button" class="secondary-button" id="closeFinancial">Fermer</button></div></form></section>`);
    const panel = node.lastElementChild;
    panel.querySelector("#closeFinancial").addEventListener("click", () => panel.remove());
    panel.querySelector("form").addEventListener("submit", async event => {
        event.preventDefault(); const form = new FormData(event.currentTarget);
        const aids = form.getAll("aid").map(id => accounting.aids.find(aid => String(aid.id) === String(id))).filter(Boolean).map(aid => ({ name: aid.name, amount: aid.amount, calculationMode: aid.calculationMode, aidType: aid.aidType, description: aid.description }));
        const result = await api(`/api/accounting/documents/${document.id}/financial-data`, { method: "PUT", body: JSON.stringify({ discountMode: form.get("discountMode"), discountAmount: form.get("discountAmount"), depositAmount: form.get("depositAmount"), conditions: form.get("conditions"), comments: form.get("comments"), aids }) });
        if (!result.ok) { panel.querySelector("#financialMessage").textContent = result.message || "Enregistrement impossible."; panel.querySelector("#financialMessage").classList.add("error"); return; }
        renderAccounting("quotes");
    });
}

function renderSettlementForm(node, document) {
    node.insertAdjacentHTML("beforeend", `<section class="accounting-panel accounting-inline-form"><div class="form-heading"><div><p class="eyebrow">${escapeHtml(document.documentNumber)}</p><h3>Enregistrer un règlement</h3><p class="muted">Solde restant : ${money(document.remainingAmount)}</p></div></div><form id="settlementForm"><div class="form-grid"><label>Date<input name="date" type="date" required value="${today()}"></label><label>Montant<input name="amount" type="number" min="0.01" max="${document.remainingAmount}" step="0.01" required value="${document.remainingAmount}"></label><label>Mode<select name="method"><option>Virement</option><option>Carte bancaire</option><option>Chèque</option><option>Espèces</option><option>Prélèvement</option><option>Autre</option></select></label><label>Référence<input name="reference" maxlength="160"></label><label class="form-wide">Note<textarea name="notes" rows="2"></textarea></label></div><p class="auth-message"></p><div class="calendar-form-actions"><button class="secondary-button">Enregistrer le règlement</button><button type="button" class="secondary-button" data-close>Fermer</button></div></form></section>`);
    const panel = node.lastElementChild; panel.querySelector("[data-close]").addEventListener("click", () => panel.remove());
    panel.querySelector("form").addEventListener("submit", async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const result = await api("/api/accounting/settlements", { method: "POST", body: JSON.stringify({ ...values, documentId: document.id }) }); if (!result.ok) { const message = panel.querySelector(".auth-message"); message.textContent = result.message || "Règlement impossible."; message.classList.add("error"); return; } renderAccounting("invoices"); });
}

async function createCredit(documentId) {
    const amount = window.prompt("Montant TTC de l’avoir :"); if (amount === null) return;
    const notes = window.prompt("Motif de l’avoir (facultatif) :", "") ?? "";
    const result = await api(`/api/accounting/documents/${encodeURIComponent(documentId)}/credits`, { method: "POST", body: JSON.stringify({ amount, notes }) });
    if (!result.ok) return alert(result.message || "Création de l’avoir impossible.");
    renderAccounting("invoices");
}

function renderExports(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Interopérabilité</p><h3>Assistant d’export comptable</h3><p class="muted">CSV, Excel, PDF et FEC ; bases prêtes pour Sage, EBP, Cegid, Pennylane, MyUnisoft et Quadra.</p></div></div><form id="exportForm" class="form-grid"><label>Données<select name="scope"><option value="all">Toutes les données</option><option value="invoices">Factures</option><option value="quotes">Devis</option><option value="credits">Avoirs</option><option value="settlements">Règlements</option><option value="clients">Clients</option><option value="overdue">Impayés</option><option value="fec">FEC (écritures)</option></select></label><label>Format<select name="format"><option value="csv">CSV</option><option value="xlsx">Excel (.xlsx)</option><option value="pdf">PDF</option><option value="fec">FEC (.txt)</option></select></label><label>Date de début<input name="start" type="date"></label><label>Date de fin<input name="end" type="date"></label><div class="form-actions"><button class="secondary-button">Télécharger l’export</button></div></form></section>`;
    const form = node.querySelector("form"); form.addEventListener("submit", event => { event.preventDefault(); const values = Object.fromEntries(new FormData(form)); if (values.format === "fec") values.scope = "fec"; window.location.href = `/api/accounting/export?${new URLSearchParams(values)}`; });
}

function renderElectronic(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Réforme française</p><h3>Facturation électronique / PDP</h3><p class="muted">Connecteurs isolés, journal des échanges, suivi des statuts et possibilité de renvoi.</p></div></div><div class="accounting-transmission-list">${accounting.transmissions.length ? accounting.transmissions.map(item => `<article><div><strong>${escapeHtml(item.documentNumber)}</strong><p>${escapeHtml(item.provider)} · ${escapeHtml(item.status)}</p><small>${escapeHtml(item.message || "Aucun message")}</small></div><button type="button" class="secondary-button" data-transmit="${item.documentId}">Renvoyer</button></article>`).join("") : '<p class="muted">Aucune transmission pour le moment.</p>'}</div><h4>Factures prêtes à transmettre</h4><div class="accounting-transmission-list">${accounting.documents.filter(item => item.documentType === "invoice").map(item => `<article><div><strong>${escapeHtml(item.documentNumber)}</strong><p>${escapeHtml(item.customerName)} · ${money(item.totals.netPayable)}</p></div><button type="button" class="secondary-button" data-transmit="${item.id}">Transmettre</button></article>`).join("") || '<p class="muted">Aucune facture disponible.</p>'}</div></section>`;
    node.querySelectorAll("[data-transmit]").forEach(button => button.addEventListener("click", async () => { button.disabled = true; const result = await api(`/api/accounting/e-invoices/${button.dataset.transmit}/transmit`, { method: "POST" }); if (!result.ok) alert(result.message || "Transmission impossible."); renderAccounting("electronic"); }));
}

function renderAids(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Moteur évolutif</p><h3>Aides financières</h3><p class="muted">Les règles de travaux, équipement, client et localisation sont enregistrées indépendamment pour un futur moteur de calcul actualisable.</p></div></div><form id="aidForm" class="form-grid"><label>Nom *<input name="name" required maxlength="160" placeholder="Ex. Certificats d’Économies d’Énergie"></label><label>Type<select name="aidType">${Object.entries(AID_TYPES).map(([id, label]) => `<option value="${id}">${escapeHtml(label)}</option>`).join("")}</select></label><label>Calcul<select name="calculationMode"><option value="fixed">Montant fixe (€)</option><option value="percentage">Pourcentage (%)</option></select></label><label>Montant *<input name="amount" type="number" min="0" step="0.01" required></label><label class="accounting-switch"><input name="autoApply" type="checkbox"> Appliquer automatiquement aux nouveaux devis</label><label class="form-wide">Description<textarea name="description" rows="2" maxlength="1000"></textarea></label><fieldset class="accounting-rules form-wide"><legend>Critères préparatoires du moteur automatique</legend><label>Type de travaux<input name="workType" maxlength="120"></label><label>Matériel installé<input name="equipment" maxlength="120"></label><label>Catégorie client<input name="customerCategory" maxlength="120"></label><label>Localisation<input name="location" maxlength="120"></label></fieldset><div class="form-actions"><button class="secondary-button">Ajouter l’aide</button></div></form><div class="accounting-aid-list">${accounting.aids.map(aid => `<article><div><strong>${escapeHtml(aid.name)}</strong><p>${escapeHtml(AID_TYPES[aid.aidType] || "Autre")} · ${aid.calculationMode === "percentage" ? `${aid.amount} %` : money(aid.amount)}${aid.autoApply ? " · automatique" : ""}</p><small>${escapeHtml(aid.description || "Sans description")}</small></div><button type="button" class="danger-button" data-delete-aid="${aid.id}">Supprimer</button></article>`).join("") || '<p class="muted">Aucune aide configurée.</p>'}</div></section>`;
    node.querySelector("#aidForm").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { ...Object.fromEntries(form), autoApply: form.get("autoApply") === "on", rules: { workType: form.get("workType"), equipment: form.get("equipment"), customerCategory: form.get("customerCategory"), location: form.get("location") } }; const result = await api("/api/accounting/aids", { method: "POST", body: JSON.stringify(payload) }); if (!result.ok) return alert(result.message || "Ajout impossible."); renderAccounting("aids"); });
    node.querySelectorAll("[data-delete-aid]").forEach(button => button.addEventListener("click", async () => { if (!confirm("Supprimer cette aide ?")) return; const result = await api(`/api/accounting/aids/${button.dataset.deleteAid}`, { method: "DELETE" }); if (!result.ok) return alert(result.message || "Suppression impossible."); renderAccounting("aids"); }));
}

function renderSettings(node) {
    const settings = accounting.settings;
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Paramètres entreprise et PDP</p><h3>Paramètres comptables</h3><p class="muted">Les coordonnées société, SIREN/SIRET, TVA, IBAN, logo et mentions légales restent configurés dans « Devis & factures ».</p></div></div><form id="accountingSettingsForm" class="form-grid"><fieldset class="accounting-rules form-wide"><legend>Plan comptable</legend><label>Compte ventes<input name="salesAccount" value="${escapeHtml(settings.chartConfig.salesAccount || "706000")}"></label><label>Compte clients<input name="customerAccount" value="${escapeHtml(settings.chartConfig.customerAccount || "411000")}"></label><label>Compte banque<input name="bankAccount" value="${escapeHtml(settings.chartConfig.bankAccount || "512000")}"></label><label>TVA collectée<input name="vatCollectedAccount" value="${escapeHtml(settings.chartConfig.vatCollectedAccount || "445710")}"></label><label>Compte achats<input name="purchaseAccount" value="${escapeHtml(settings.chartConfig.purchaseAccount || "606000")}"></label><label>Compte fournisseurs<input name="supplierAccount" value="${escapeHtml(settings.chartConfig.supplierAccount || "401000")}"></label></fieldset><fieldset class="accounting-rules form-wide"><legend>Plateforme de dématérialisation partenaire</legend><label>Connecteur<select name="provider">${accounting.connectors.map(connector => `<option value="${connector.id}" ${settings.pdpProvider === connector.id ? "selected" : ""}>${escapeHtml(connector.label)}</option>`).join("")}</select></label><label>Identifiant PDP<input name="identifier" value="${escapeHtml(settings.pdpIdentifier || "")}" maxlength="160"></label><label>Clé API${settings.hasApiKey ? " (laisser vide pour conserver)" : ""}<input name="apiKey" type="password" autocomplete="new-password"></label><label class="accounting-switch"><input name="enabled" type="checkbox" ${settings.pdpEnabled ? "checked" : ""}> Activer le connecteur PDP</label></fieldset><fieldset class="accounting-rules form-wide"><legend>Moteur d’aides</legend><label class="accounting-switch"><input name="aidEngineEnabled" type="checkbox" ${settings.aidEngineConfig.enabled ? "checked" : ""}> Préparer la suggestion automatique</label><label>Source de règles future<input name="aidEngineSource" value="${escapeHtml(settings.aidEngineConfig.source || "")}" maxlength="160" placeholder="API nationale, référentiel régional…"></label></fieldset><p class="auth-message"></p><div class="form-actions"><button class="secondary-button">Enregistrer les paramètres comptables</button></div></form></section>`;
    node.querySelector("form").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { provider: form.get("provider"), identifier: form.get("identifier"), apiKey: form.get("apiKey"), enabled: form.get("enabled") === "on", chartConfig: Object.fromEntries(["salesAccount", "customerAccount", "bankAccount", "vatCollectedAccount", "purchaseAccount", "supplierAccount"].map(key => [key, form.get(key)])), aidEngineConfig: { enabled: form.get("aidEngineEnabled") === "on", source: form.get("aidEngineSource") } }; const result = await api("/api/accounting/settings", { method: "PUT", body: JSON.stringify(payload) }); if (!result.ok) return alert(result.message || "Enregistrement impossible."); renderAccounting("settings"); });
}

function renderPaymentRows(documents) { return documents.length ? `<div class="accounting-document-list">${documents.map(item => `<article class="accounting-document"><div><strong>${escapeHtml(item.documentNumber)}</strong><p>${escapeHtml(item.customerName)}</p></div><div class="accounting-document-totals"><strong>${money(item.remainingAmount)}</strong><small>${escapeHtml(paymentLabel(item))}</small></div></article>`).join("")}</div>` : '<p class="muted">Aucun impayé ni règlement en attente.</p>'; }
function paymentLabel(item) { return ({ paid: "Réglée", partial: "Partiellement réglée", overdue: "Impayée / échue", unpaid: "À encaisser" })[item.paymentStatus] || "Non concerné"; }
function money(value) { return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(Number(value) || 0); }
function date(value) { return value ? new Intl.DateTimeFormat("fr-FR").format(new Date(`${value}T12:00:00`)) : "Non renseignée"; }
function today() { return new Date().toISOString().slice(0, 10); }
async function api(url, options = {}) { try { const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => null); return { ok: response.ok, data, message: data?.message }; } catch { return { ok: false, message: "Serveur indisponible." }; } }
