import { ROUTES } from "./config.js?v=119";
import { clearSearch, getContainer, setPage } from "./ui.js?v=44";
import { escapeHtml, normalizeText } from "./utils.js?v=44";

const TABS = [["dashboard", "Tableau de bord"], ["operations", "Documents & paiements"], ["electronic", "Facturation électronique & PDP"], ["journals", "Journaux comptables"], ["exports", "Exports"]];
let sandbox = null;
let activeTab = "dashboard";

export async function renderAccountingSandbox(tab = activeTab) {
    activeTab = TABS.some(([id]) => id === tab) ? tab : "dashboard";
    clearSearch();
    setPage("Sandbox comptabilité", ROUTES.accountingSandbox, "detail");
    const container = getContainer();
    container.innerHTML = '<section class="accounting-sandbox-shell"><p class="muted">Chargement du laboratoire comptable…</p></section>';
    const result = await api("/api/accounting-sandbox/workspace");
    if (result.ok) { sandbox = result.data.sandbox; renderWorkspace(container.querySelector(".accounting-sandbox-shell")); return; }
    if (result.status === 404) return renderActivation(container.querySelector(".accounting-sandbox-shell"));
    container.innerHTML = `<section class="client-panel"><p class="auth-message error">${escapeHtml(result.message || "Impossible de charger le laboratoire comptable.")}</p></section>`;
}

function renderActivation(shell) {
    shell.innerHTML = `<section class="client-panel accounting-sandbox-activation"><p class="eyebrow">Développement · démonstration · recette</p><h2>Laboratoire Comptabilité · Facturation électronique & PDP</h2><p>Préparez instantanément une entreprise fictive, clients, interventions clôturées, devis, factures, règlements, avoirs, journaux, exports et réponses PDP simulées.</p><p class="sandbox-warning">Aucune donnée réelle, aucune écriture comptable réelle, aucun export de votre entreprise et aucune communication avec une PDP officielle ne sont utilisés.</p><button class="secondary-button" id="activateAccountingSandbox">Activer le laboratoire comptable</button></section>`;
    shell.querySelector("#activateAccountingSandbox").addEventListener("click", async event => { event.currentTarget.disabled = true; event.currentTarget.textContent = "Génération des données fictives…"; const result = await api("/api/accounting-sandbox/activate", { method: "POST" }); if (!result.ok) return alert(result.message || "Activation impossible."); sandbox = result.data.sandbox; renderWorkspace(shell); });
}

function renderWorkspace(shell) {
    const dashboard = sandbox.dashboard;
    shell.innerHTML = `<header class="accounting-sandbox-heading"><div><p class="eyebrow">Environnement fictif et isolé</p><h2>Sandbox · Comptabilité · Facturation électronique & PDP</h2><p class="muted"><strong>${escapeHtml(sandbox.company.name)}</strong> · ${escapeHtml(sandbox.company.registration)} · Aucun échange avec une plateforme officielle.</p></div><div class="accounting-sandbox-header-actions"><button class="secondary-button" data-sandbox-action="new_invoice">Nouvelle facture</button><button class="secondary-button danger-button" id="resetAccountingSandbox">Réinitialiser les données</button></div></header><section class="sandbox-warning-banner"><strong>Laboratoire de recette uniquement.</strong> Toutes les écritures, transmissions PDP et fichiers exportés ci-dessous sont générés depuis des données fictives stockées séparément.</section><nav class="accounting-tabs" aria-label="Sections du laboratoire">${TABS.map(([id, label]) => `<button type="button" class="secondary-button${id === activeTab ? " active" : ""}" data-accounting-sandbox-tab="${id}">${label}</button>`).join("")}</nav><section id="accountingSandboxContent"></section>`;
    const content = shell.querySelector("#accountingSandboxContent");
    ({ dashboard: () => renderDashboard(content, dashboard), operations: () => renderOperations(content), electronic: () => renderElectronic(content), journals: () => renderJournals(content), exports: () => renderExports(content) })[activeTab]();
    shell.querySelectorAll("[data-accounting-sandbox-tab]").forEach(button => button.addEventListener("click", () => renderAccountingSandbox(button.dataset.accountingSandboxTab)));
    shell.querySelectorAll("[data-sandbox-action]").forEach(button => button.addEventListener("click", () => runAction(button.dataset.sandboxAction)));
    shell.querySelector("#resetAccountingSandbox").addEventListener("click", resetSandbox);
}

function renderDashboard(node, data) {
    node.innerHTML = `<div class="accounting-cards accounting-sandbox-cards"><article><span>Chiffre d’affaires</span><strong>${money(data.turnover)}</strong><small>Fictif</small></article><article><span>Factures émises</span><strong>${data.invoicesIssued}</strong><small>${data.paid} payée(s)</small></article><article><span>En attente</span><strong>${data.pending}</strong><small>Factures à suivre</small></article><article><span>TVA collectée</span><strong>${money(data.vatCollected)}</strong><small>TVA restante ${money(data.vatRemaining)}</small></article><article><span>Encaissements du mois</span><strong>${money(data.monthReceipts)}</strong><small>Avoirs ${money(data.credits)}</small></article></div><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Jeu de données généré</p><h3>Entreprise, clients et interventions terminées</h3></div></div><div class="accounting-sandbox-columns"><div><h4>Clients fictifs</h4><ul class="accounting-sandbox-simple-list">${sandbox.clients.map(item => `<li><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.address)}</small></li>`).join("")}</ul></div><div><h4>Interventions clôturées</h4><ul class="accounting-sandbox-simple-list">${sandbox.interventions.map(item => `<li><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.customerName)} · ${escapeHtml(item.technician)} · Rapport terminé · Clôturée</small></li>`).join("")}</ul></div></div></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Scénarios rapides</p><h3>Tester le cycle comptable</h3></div></div><div class="accounting-sandbox-actions">${button("new_invoice", "Générer une nouvelle facture")}${button("new_quote", "Générer un devis")}${button("quote_to_invoice", "Transformer un devis en facture")}${button("payment", "Simuler un paiement")}${button("overdue", "Simuler un impayé")}${button("partial_credit", "Générer un avoir partiel")}${button("total_credit", "Générer un avoir total")}${button("pdp_rejected", "Simuler un rejet électronique")}${button("pdp_accepted", "Simuler une acceptation")}</div></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Traçabilité locale</p><h3>Chronologie Sandbox</h3></div></div><ol class="accounting-sandbox-timeline">${sandbox.timeline.slice(0, 15).map(item => `<li><time>${escapeHtml(dateTime(item.occurredAt))}</time><strong>${escapeHtml(item.label)}</strong></li>`).join("")}</ol></section>`;
    node.querySelectorAll("[data-sandbox-action]").forEach(bindAction);
}

function renderOperations(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Devis et factures fictifs</p><h3>Documents, montants, TVA et soldes</h3></div><input id="sandboxDocumentSearch" class="accounting-search" type="search" placeholder="Rechercher un client ou un document"></div><div id="sandboxDocuments"></div></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Règlements simulés</p><h3>Virements, cartes, espèces, chèques, acomptes et paiements partiels</h3></div></div><div class="accounting-document-list">${sandbox.payments.map(item => `<article class="accounting-document"><div><strong>${escapeHtml(item.invoiceNumber)}</strong><p>${escapeHtml(item.customerName)}</p><small>${escapeHtml(date(item.date))} · ${escapeHtml(item.reference)}</small></div><div class="accounting-document-totals"><strong>${money(item.amount)}</strong><small>${escapeHtml(item.method)}</small></div></article>`).join("")}</div></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Avoirs fictifs</p><h3>Impacts comptables intégrés aux exports et journaux</h3></div></div><div class="accounting-document-list">${sandbox.credits.map(item => `<article class="accounting-document"><div><strong>${escapeHtml(item.number)}</strong><p>${escapeHtml(item.invoiceNumber)} · ${escapeHtml(item.customerName)}</p><small>${escapeHtml(item.reason)}</small></div><div class="accounting-document-totals"><strong>${money(item.amount)}</strong><small>${escapeHtml(date(item.date))}</small></div></article>`).join("")}</div></section>`;
    const list = node.querySelector("#sandboxDocuments");
    const render = () => { const query = normalizeText(node.querySelector("#sandboxDocumentSearch").value); const items = [...sandbox.quotes, ...sandbox.invoices].filter(item => !query || normalizeText(`${item.number} ${item.customer.name}`).includes(query)); list.innerHTML = items.map(documentItem).join("") || '<p class="muted">Aucun document trouvé.</p>'; };
    node.querySelector("#sandboxDocumentSearch").addEventListener("input", render); render();
}

function renderElectronic(node) {
    const invoices = sandbox.invoices.filter(item => !["draft", "cancelled"].includes(item.status));
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">PDP locale simulée</p><h3>Facturation électronique & PDP</h3><p class="muted">Même contrat d’interface qu’un connecteur futur, sans URL, clé API ni communication externe.</p></div></div><div class="accounting-sandbox-actions">${invoices.map(item => `<button type="button" class="secondary-button" data-pdp-transmit="${escapeHtml(item.id)}">Simuler un envoi PDP · ${escapeHtml(item.number)}</button>`).join("")}</div></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Réponses de plateforme</p><h3>Déclencher une réponse simulée</h3></div></div><div class="accounting-sandbox-actions">${["processing", "accepted", "rejected", "format_error", "recipient_not_found", "distributed"].map(outcome => `<button type="button" class="secondary-button" data-pdp-outcome="${outcome}">${escapeHtml(pdpLabel(outcome))}</button>`).join("")}</div><p class="muted">La réponse est appliquée à une facture fictive disponible ; elle alimente la chronologie ci-dessous.</p></section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Chronologie des échanges</p><h3>Journal PDP simulé</h3></div></div><ol class="accounting-sandbox-timeline">${sandbox.transmissions.map(item => `<li><time>${escapeHtml(dateTime(item.occurredAt))}</time><strong>${escapeHtml(item.invoiceNumber)} · ${escapeHtml(pdpLabel(item.status))}</strong><small>${escapeHtml(item.message)} · ${escapeHtml(item.remoteId)}</small></li>`).join("") || '<p class="muted">Aucune transmission simulée.</p>'}</ol></section>`;
    node.querySelectorAll("[data-pdp-transmit]").forEach(button => button.addEventListener("click", () => transmit(button.dataset.pdpTransmit)));
    node.querySelectorAll("[data-pdp-outcome]").forEach(button => button.addEventListener("click", () => runAction(`pdp_${button.dataset.pdpOutcome}`)));
}

function renderJournals(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Écritures de démonstration</p><h3>Journal des ventes</h3></div></div>${journalTable(sandbox.journals.sales)}</section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Encaissements</p><h3>Journal des règlements</h3></div></div>${journalTable(sandbox.journals.settlements)}</section><section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Corrections</p><h3>Journal des avoirs</h3></div></div>${journalTable(sandbox.journals.credits)}</section>`;
}

function renderExports(node) {
    node.innerHTML = `<section class="accounting-panel"><div class="form-heading"><div><p class="eyebrow">Fichiers de validation</p><h3>Exports comptables fictifs</h3><p class="muted">CSV, Excel, FEC et export générique sont construits exclusivement à partir de la Sandbox.</p></div></div><form id="sandboxExportForm" class="form-grid"><label>Données<select name="scope"><option value="all">Export comptable générique</option><option value="invoices">Factures</option><option value="quotes">Devis</option><option value="credits">Avoirs</option><option value="payments">Règlements</option><option value="journals">Journaux comptables</option></select></label><label>Format<select name="format"><option value="csv">CSV</option><option value="xlsx">Excel (.xlsx)</option><option value="fec">FEC (.txt)</option></select></label><div class="form-actions"><button class="secondary-button">Télécharger l’export</button></div></form></section>`;
    node.querySelector("#sandboxExportForm").addEventListener("submit", event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); window.location.href = `/api/accounting-sandbox/export?${new URLSearchParams(values)}`; });
}

function documentItem(item) { const totals = item.totals || calculateTotals(item); const isInvoice = item.type === "invoice"; return `<article class="accounting-document"><div><p class="eyebrow">${escapeHtml(item.number)} · ${escapeHtml(statusLabel(item.status))}</p><h4>${escapeHtml(item.customer.name)}</h4><small>${escapeHtml(date(item.issueDate))}${item.quoteNumber ? ` · Issu de ${escapeHtml(item.quoteNumber)}` : ""}</small><p class="muted">${escapeHtml(item.lines.map(line => line.description).join(" · "))}</p></div><div class="accounting-document-totals"><strong>${money(totals.ttc)}</strong><small>HT ${money(totals.ht)} · TVA ${money(totals.vat)}${isInvoice ? ` · Solde ${money(item.remainingAmount)}` : ""}</small></div></article>`; }
function journalTable(rows) { return `<div class="accounting-sandbox-table-wrap"><table class="accounting-sandbox-table"><thead><tr><th>Date</th><th>Compte</th><th>Libellé</th><th>Référence</th><th>Débit</th><th>Crédit</th></tr></thead><tbody>${rows.map(item => `<tr><td>${escapeHtml(date(item.date))}</td><td>${escapeHtml(item.account)}</td><td>${escapeHtml(item.label)}</td><td>${escapeHtml(item.reference)}</td><td>${money(item.debit)}</td><td>${money(item.credit)}</td></tr>`).join("")}</tbody></table></div>`; }
function button(action, label) { return `<button type="button" class="secondary-button" data-sandbox-action="${action}">${label}</button>`; }
function bindAction(button) { button.addEventListener("click", () => runAction(button.dataset.sandboxAction)); }
async function runAction(action) { const result = await api(`/api/accounting-sandbox/actions/${encodeURIComponent(action)}`, { method: "POST" }); if (!result.ok) return alert(result.message || "Simulation impossible."); sandbox = result.data.sandbox; renderAccountingSandbox(activeTab); }
async function transmit(invoiceId) { const result = await api(`/api/accounting-sandbox/e-invoices/${encodeURIComponent(invoiceId)}/transmit`, { method: "POST" }); if (!result.ok) return alert(result.message || "Envoi simulé impossible."); sandbox = result.data.sandbox; renderAccountingSandbox("electronic"); }
async function resetSandbox() { if (!confirm("Réinitialiser toutes les données comptables de démonstration ?")) return; const result = await api("/api/accounting-sandbox", { method: "DELETE" }); if (!result.ok) return alert(result.message || "Réinitialisation impossible."); sandbox = null; renderAccountingSandbox(); }
function calculateTotals(item) { const ht = item.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0); const vat = item.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice * line.vatRate / 100, 0); return { ht, vat, ttc: ht + vat }; }
function statusLabel(value) { return ({ draft: "Brouillon", validated: "Validée", sent: "Envoyée", paid: "Payée", partial: "Partiellement réglée", overdue: "Impayée", cancelled: "Annulée", accepted: "Accepté", rejected: "Refusé", pending: "En attente" })[value] || value; }
function pdpLabel(value) { return ({ received: "Facture reçue", accepted: "Facture acceptée", processing: "En cours de traitement", rejected: "Facture rejetée", format_error: "Erreur de format", recipient_not_found: "Destinataire introuvable", distributed: "Facture distribuée" })[value] || value; }
function money(value) { return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(Number(value) || 0); }
function date(value) { return value ? new Intl.DateTimeFormat("fr-FR").format(new Date(`${value}T12:00:00`)) : "—"; }
function dateTime(value) { return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
async function api(url, options = {}) { try { const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => null); return { ok: response.ok, status: response.status, data, message: data?.message }; } catch { return { ok: false, message: "Serveur indisponible." }; } }
