import { ROUTES } from "./config.js?v=117";
import { clearSearch, getContainer, setPage } from "./ui.js?v=44";
import { escapeHtml, normalizeText } from "./utils.js?v=44";

const SECTIONS = [["new", "Nouveau connecteur"], ["installed", "Connecteurs installés"], ["edit", "Modifier un connecteur"], ["test", "Tester un connecteur"], ["generator", "Générateur de connecteur"], ["documentation", "Documentation"]];
const DEPANNHOME_FIELDS = ["Nom du client", "Adresse d’intervention", "Téléphone", "Numéro de dossier / référence", "Rendez-vous", "Niveau d’urgence", "État de l’intervention", "E-mail", "Description de la mission", "Montant du devis", "Statut de facture"];
let data = null;
let activeSection = "new";
let selectedId = 0;
let creatorMode = false;

export function renderCreatorConnectors() { creatorMode = true; return renderConnectors(); }

export async function renderConnectors(section = activeSection, connectorId = selectedId) {
    activeSection = SECTIONS.some(([id]) => id === section) ? section : "new"; selectedId = Number(connectorId) || 0;
    clearSearch(); setPage("Prestataires externes", ROUTES.creator, "detail");
    const container = getContainer(); container.innerHTML = '<section class="client-panel connectors-shell"><p class="muted">Chargement des connecteurs…</p></section>';
    const result = await api("/api/connectors");
    if (!result.ok) { container.innerHTML = `<section class="client-panel"><p class="auth-message error">${escapeHtml(result.message || "Impossible de charger les connecteurs.")}</p></section>`; return; }
    data = result.data; const shell = container.querySelector(".connectors-shell");
    shell.innerHTML = `<header class="connectors-heading"><div><p class="eyebrow">Administration plateforme</p><h2>Base de prestataires externes</h2><p class="muted">Créez, testez, exportez et enrichissez le registre des intégrations partenaires, sans exposer ces réglages aux entreprises.</p></div><div class="connector-header-actions">${creatorMode ? '<button type="button" class="secondary-button" id="backToCreator">Retour à la console</button>' : ""}<label class="secondary-button connector-import">Importer un paquet<input type="file" accept="application/json,.json" id="connectorImport"></label></div></header><nav class="connector-tabs">${SECTIONS.map(([id, label]) => `<button type="button" class="secondary-button${id === activeSection ? " active" : ""}" data-section="${id}">${label}</button>`).join("")}</nav><section id="connectorsContent"></section>`;
    shell.querySelector("#backToCreator")?.addEventListener("click", async () => { creatorMode = false; const { renderCreatorConsole } = await import("./creator.js?v=123"); renderCreatorConsole(); });
    shell.querySelectorAll("[data-section]").forEach(button => button.addEventListener("click", () => renderConnectors(button.dataset.section, selectedId)));
    shell.querySelector("#connectorImport").addEventListener("change", importBundle);
    const content = shell.querySelector("#connectorsContent");
    ({ new: renderWizard, installed: renderInstalled, edit: renderEdit, test: renderTest, generator: renderGenerator, documentation: renderDocumentation })[activeSection](content);
    content.querySelectorAll("[data-choose]").forEach(button => button.addEventListener("click", () => renderConnectors(activeSection, button.dataset.choose)));
}

function renderWizard(node) {
    node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">Assistant étape par étape</p><h3>Nouveau connecteur</h3><p class="muted">Les secrets sont chiffrés côté serveur et ne figurent jamais dans les exports.</p></div></div><form id="connectorWizard"><div class="connector-wizard-steps"><span>1. Informations</span><span>2. Connexion</span><span>3. Endpoints</span><span>4. Mapping</span></div><fieldset><legend>Informations générales</legend><div class="form-grid"><label>Nom du partenaire *<input name="name" required maxlength="160" placeholder="Ex. Assistance Exemple"></label><label>Version<input name="version" maxlength="40" value="1.0.0"></label><label>Auteur<input name="author" maxlength="160"></label><label>Site web<input name="website" type="url"></label><label>URL du logo<input name="logoUrl" type="url" placeholder="https://…"></label><label class="form-wide">Description<textarea name="description" rows="2" maxlength="2000"></textarea></label></div></fieldset><fieldset><legend>Connexion</legend><div class="form-grid"><label>Authentification *<select name="authType">${data.capabilities.authTypes.map(type => `<option value="${type}">${authLabel(type)}</option>`).join("")}</select></label><label>URL de base HTTPS *<input name="baseUrl" type="url" required placeholder="https://api.partenaire.fr"></label><label>URL de test<input name="testUrl" type="url" placeholder="https://sandbox.partenaire.fr"></label><label>URL de production<input name="productionUrl" type="url"></label><label>Timeout (ms)<input name="timeout" type="number" min="1000" max="60000" value="15000"></label><label>Tentatives maximales<input name="maxRetries" type="number" min="0" max="5" value="2"></label><label>Fréquence de synchro (minutes)<input name="syncMinutes" type="number" min="5" max="10080" value="60"></label></div><div class="connector-credentials" id="credentialFields"></div></fieldset><fieldset><legend>Endpoints</legend><p class="muted">Ajoutez les opérations du partenaire : missions, devis, factures, pièces jointes ou statuts.</p><div id="endpointRows"></div><button type="button" class="secondary-button" id="addEndpoint">Ajouter un endpoint</button></fieldset><fieldset><legend>Mapping des données</legend><div id="mappingRows"></div><button type="button" class="secondary-button" id="addMapping">Ajouter un mapping</button></fieldset><p class="auth-message" id="wizardMessage"></p><div class="form-actions"><button class="secondary-button">Installer le connecteur</button></div></form></section>`;
    const form = node.querySelector("form"); const credentials = node.querySelector("#credentialFields"); const endpoints = node.querySelector("#endpointRows"); const mappings = node.querySelector("#mappingRows");
    const refreshCredentials = () => credentials.innerHTML = credentialInputs(form.authType.value);
    form.authType.addEventListener("change", refreshCredentials); refreshCredentials();
    node.querySelector("#addEndpoint").addEventListener("click", () => addEndpoint(endpoints)); addEndpoint(endpoints);
    node.querySelector("#addMapping").addEventListener("click", () => addMapping(mappings)); addMapping(mappings);
    form.addEventListener("submit", async event => { event.preventDefault(); const payload = readConnectorForm(form); const result = await api("/api/connectors", { method: "POST", body: JSON.stringify(payload) }); const message = node.querySelector("#wizardMessage"); if (!result.ok) { message.textContent = result.message || "Installation impossible."; message.classList.add("error"); return; } selectedId = result.data.id; renderConnectors("installed", selectedId); });
}

function renderInstalled(node) {
    const connectors = data.connectors;
    node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">Registre de plugins</p><h3>Connecteurs installés</h3></div><input type="search" id="connectorSearch" placeholder="Rechercher un partenaire"></div><div id="connectorList" class="connector-list"></div></section>`;
    const list = node.querySelector("#connectorList"); const render = () => { const query = normalizeText(node.querySelector("#connectorSearch").value); const items = connectors.filter(item => !query || normalizeText(`${item.manifest.general.name} ${item.connectorKey}`).includes(query)); list.innerHTML = items.length ? items.map(connectorCard).join("") : '<p class="muted">Aucun connecteur installé.</p>'; bindConnectorCards(list); };
    node.querySelector("#connectorSearch").addEventListener("input", render); render();
}
function connectorCard(item) { const general = item.manifest.general; return `<article class="connector-card"><div class="connector-logo">${general.logoUrl ? `<img src="${escapeHtml(general.logoUrl)}" alt="" onerror="this.remove()">` : "API"}</div><div class="connector-card-main"><p class="eyebrow">${escapeHtml(item.connectorKey)} · v${escapeHtml(general.version)}</p><h4>${escapeHtml(general.name)}</h4><p>${escapeHtml(general.description || "Sans description")}</p><small>${item.manifest.endpoints.length} point(s) d’accès · ${authLabel(item.manifest.connection.authType)} · ${item.hasCredentials ? "secrets configurés" : "secrets à configurer"}</small></div><span class="connector-status ${item.enabled ? "enabled" : "disabled"}">${item.enabled ? "Actif" : "Désactivé"}</span><div class="connector-actions"><button class="secondary-button" data-edit="${item.id}">Modifier</button><button class="secondary-button" data-test="${item.id}">Tester</button><button class="secondary-button" data-toggle="${item.id}">${item.enabled ? "Désactiver" : "Activer"}</button><button class="danger-button" data-delete="${item.id}">Supprimer</button></div></article>`; }
function bindConnectorCards(node) { node.querySelectorAll("[data-edit]").forEach(button => button.addEventListener("click", () => renderConnectors("edit", button.dataset.edit))); node.querySelectorAll("[data-test]").forEach(button => button.addEventListener("click", () => renderConnectors("test", button.dataset.test))); node.querySelectorAll("[data-toggle]").forEach(button => button.addEventListener("click", () => toggleConnector(button.dataset.toggle))); node.querySelectorAll("[data-delete]").forEach(button => button.addEventListener("click", () => deleteConnector(button.dataset.delete))); }

function renderEdit(node) {
    const connector = selectedConnector(); if (!connector) { node.innerHTML = chooseConnector("modifier"); return; }
    const manifest = connector.manifest; node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">${escapeHtml(connector.connectorKey)}</p><h3>Modifier un connecteur</h3></div><button type="button" class="secondary-button" id="backInstalled">Liste</button></div><form id="connectorEdit"><div class="form-grid"><label>Nom *<input name="name" required value="${escapeHtml(manifest.general.name)}"></label><label>Version<input name="version" value="${escapeHtml(manifest.general.version)}"></label><label>Auteur<input name="author" value="${escapeHtml(manifest.general.author)}"></label><label>Site web<input name="website" type="url" value="${escapeHtml(manifest.general.website)}"></label><label>URL du logo<input name="logoUrl" type="url" value="${escapeHtml(manifest.general.logoUrl)}"></label><label class="form-wide">Description<textarea name="description" rows="2">${escapeHtml(manifest.general.description)}</textarea></label><label>Authentification<select name="authType">${data.capabilities.authTypes.map(type => `<option value="${type}" ${manifest.connection.authType === type ? "selected" : ""}>${authLabel(type)}</option>`).join("")}</select></label><label>URL de base *<input name="baseUrl" type="url" required value="${escapeHtml(manifest.connection.baseUrl)}"></label><label>URL de test<input name="testUrl" type="url" value="${escapeHtml(manifest.connection.testUrl)}"></label><label>URL production<input name="productionUrl" type="url" value="${escapeHtml(manifest.connection.productionUrl)}"></label><label>Timeout<input name="timeout" type="number" min="1000" max="60000" value="${manifest.connection.timeout}"></label><label>Tentatives<input name="maxRetries" type="number" min="0" max="5" value="${manifest.connection.maxRetries}"></label><label>Synchronisation (minutes)<input name="syncMinutes" type="number" min="5" max="10080" value="${manifest.connection.syncMinutes}"></label><label class="connector-switch"><input name="enabled" type="checkbox" ${connector.enabled ? "checked" : ""}> Connecteur activé</label></div><div class="connector-credentials" id="credentialFields"></div><fieldset><legend>Endpoints</legend><div id="endpointRows"></div><button type="button" class="secondary-button" id="addEndpoint">Ajouter un endpoint</button></fieldset><fieldset><legend>Mapping</legend><div id="mappingRows"></div><button type="button" class="secondary-button" id="addMapping">Ajouter un mapping</button></fieldset><p class="auth-message"></p><div class="form-actions"><button class="secondary-button">Enregistrer les modifications</button></div></form></section>`;
    node.querySelector("#backInstalled").addEventListener("click", () => renderConnectors("installed")); const form = node.querySelector("form"), endpoints = node.querySelector("#endpointRows"), mappings = node.querySelector("#mappingRows"), credentials = node.querySelector("#credentialFields");
    const refreshCredentials = () => credentials.innerHTML = `${connector.hasCredentials ? '<p class="muted">Les secrets actuels sont conservés si vous laissez ces champs vides.</p>' : ""}${credentialInputs(form.authType.value)}`; form.authType.addEventListener("change", refreshCredentials); refreshCredentials();
    manifest.endpoints.forEach(endpoint => addEndpoint(endpoints, endpoint)); manifest.mappings.forEach(mapping => addMapping(mappings, mapping)); node.querySelector("#addEndpoint").addEventListener("click", () => addEndpoint(endpoints)); node.querySelector("#addMapping").addEventListener("click", () => addMapping(mappings));
    form.addEventListener("submit", async event => { event.preventDefault(); const result = await api(`/api/connectors/${connector.id}`, { method: "PUT", body: JSON.stringify(readConnectorForm(form)) }); if (!result.ok) { const message = form.querySelector(".auth-message"); message.textContent = result.message || "Enregistrement impossible."; message.classList.add("error"); return; } renderConnectors("installed", connector.id); });
}

function renderTest(node) { const connector = selectedConnector(); if (!connector) { node.innerHTML = chooseConnector("tester"); return; } const endpoints = connector.manifest.endpoints; node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">Test sécurisé</p><h3>${escapeHtml(connector.manifest.general.name)}</h3><p class="muted">Les entêtes et secrets sont masqués dans le journal.</p></div></div><form id="connectorTest" class="form-grid"><label>Endpoint<select name="endpointId">${endpoints.map(endpoint => `<option value="${escapeHtml(endpoint.id)}">${escapeHtml(endpoint.name)} — ${endpoint.method} ${escapeHtml(endpoint.path)}</option>`).join("")}</select></label><label class="form-wide">Données de test JSON<textarea name="payload" rows="7" placeholder='{"reference":"TEST-001"}'></textarea></label><div class="form-actions"><button class="secondary-button">Envoyer la requête de test</button></div></form><pre class="connector-test-output" id="testOutput">En attente d’un test.</pre></section>`; node.querySelector("form").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); let payload = {}; try { payload = form.get("payload") ? JSON.parse(form.get("payload")) : {}; } catch { return showTestOutput(node, { ok: false, message: "Le JSON de test est invalide." }); } showTestOutput(node, { message: "Test en cours…" }); const result = await api(`/api/connectors/${connector.id}/test`, { method: "POST", body: JSON.stringify({ endpointId: form.get("endpointId"), payload }) }); showTestOutput(node, result.data || { ok: false, message: result.message }); }); }
function showTestOutput(node, result) { node.querySelector("#testOutput").textContent = JSON.stringify(result, null, 2); }
function renderGenerator(node) { const connector = selectedConnector(); node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">Paquet portable</p><h3>Générateur de connecteur</h3><p class="muted">Le paquet contient un manifeste, un modèle de synchronisation, une configuration sans secrets, des consignes de logs et la documentation.</p></div></div>${connector ? `<article class="connector-generator"><strong>${escapeHtml(connector.manifest.general.name)}</strong><p>Le connecteur reste immédiatement utilisable dans le runtime déclaré de Depann’Home Pro ; aucun code tiers n’est chargé en production.</p><a class="secondary-button" href="/api/connectors/${connector.id}/export">Télécharger le paquet de connecteur</a><a class="secondary-button" href="/api/connectors/${connector.id}/documentation">Télécharger la documentation Markdown</a></article>` : chooseConnector("générer")}</section>`; }
function renderDocumentation(node) { const connector = selectedConnector(); const logs = selectedId ? data.logs.filter(log => Number(log.connectorId) === Number(selectedId)) : data.logs; node.innerHTML = `<section class="connector-panel"><div class="form-heading"><div><p class="eyebrow">Guide & journal</p><h3>Documentation des connecteurs</h3><p class="muted">Un connecteur ne peut pas inclure de secrets dans son export. Les modifications, imports et tests sont journalisés par entreprise.</p></div></div>${connector ? `<a class="secondary-button" href="/api/connectors/${connector.id}/documentation">Télécharger ${escapeHtml(connector.manifest.general.name)}.md</a>` : ""}<h4>Historique des opérations</h4><div class="connector-log-list">${logs.length ? logs.map(log => `<article><span class="connector-status ${log.status === "success" ? "enabled" : "failed"}">${escapeHtml(logStatusLabel(log.status))}</span><div><strong>${escapeHtml(log.connectorKey)} · ${escapeHtml(logActionLabel(log.action))}</strong><p>${escapeHtml(log.message)}</p><small>${dateTime(log.createdAt)}${log.endpointName ? ` · ${escapeHtml(log.endpointName)}` : ""}</small></div></article>`).join("") : '<p class="muted">Aucune opération journalisée.</p>'}</div></section>`; }
function chooseConnector(action) { return `<section class="connector-panel"><p class="muted">Sélectionnez un connecteur installé pour ${action} sa configuration.</p><div class="connector-choice-list">${data.connectors.map(item => `<button type="button" class="secondary-button" data-choose="${item.id}">${escapeHtml(item.manifest.general.name)}</button>`).join("") || ""}</div></section>`; }
function addEndpoint(node, endpoint = {}) { const id = endpoint.id || `endpoint-${Date.now()}-${node.children.length}`; const row = document.createElement("article"); row.className = "connector-endpoint-row"; row.innerHTML = `<div class="form-grid"><label>Nom *<input data-name="endpointName" required value="${escapeHtml(endpoint.name || "")}" placeholder="Ex. Récupération des missions"></label><label>Méthode<select data-name="endpointMethod">${data.capabilities.methods.map(method => `<option ${endpoint.method === method ? "selected" : ""}>${method}</option>`).join("")}</select></label><label>Chemin *<input data-name="endpointPath" required value="${escapeHtml(endpoint.path || "")}" placeholder="/v1/missions"></label><label>Objectif<input data-name="endpointPurpose" value="${escapeHtml(endpoint.purpose || "")}" placeholder="Synchroniser les missions"></label><label class="form-wide">Paramètres JSON<textarea data-name="endpointParameters" rows="2" placeholder='{"page":"1"}'>${escapeHtml(JSON.stringify(endpoint.parameters || {}, null, 2))}</textarea></label><label class="form-wide">Headers JSON<textarea data-name="endpointHeaders" rows="2" placeholder='{"Accept":"application/json"}'>${escapeHtml(JSON.stringify(endpoint.headers || {}, null, 2))}</textarea></label><label class="form-wide">Corps JSON<textarea data-name="endpointBody" rows="2" placeholder='{"status":"new"}'>${escapeHtml(endpoint.body || "")}</textarea></label><label class="form-wide">Réponse attendue JSON<textarea data-name="endpointExpected" rows="2">${escapeHtml(endpoint.expectedResponse || "")}</textarea></label></div><button type="button" class="danger-button" data-remove>Retirer</button></article>`; row.dataset.endpointId = id; row.querySelector("[data-remove]").addEventListener("click", () => row.remove()); node.appendChild(row); }
function addMapping(node, mapping = {}) { const row = document.createElement("div"); row.className = "connector-mapping-row"; row.innerHTML = `<input data-name="apiField" placeholder="Champ API" value="${escapeHtml(mapping.apiField || "")}"><select data-name="depannhomeField"><option value="">Champ Depann’Home Pro</option>${DEPANNHOME_FIELDS.map(field => `<option ${mapping.depannhomeField === field ? "selected" : ""}>${escapeHtml(field)}</option>`).join("")}</select><input data-name="transform" placeholder="Transformation facultative" value="${escapeHtml(mapping.transform || "")}"><button type="button" class="danger-button" data-remove>×</button>`; row.querySelector("[data-remove]").addEventListener("click", () => row.remove()); node.appendChild(row); }
function readConnectorForm(form) { const value = name => form.elements[name]?.value || ""; const credentials = {}; form.querySelectorAll("[data-credential]").forEach(input => { if (input.value.trim()) credentials[input.dataset.credential] = input.value; }); return { connectorKey: slug(value("name")), general: { name: value("name"), version: value("version"), author: value("author"), website: value("website"), logoUrl: value("logoUrl"), description: value("description") }, connection: { authType: value("authType"), baseUrl: value("baseUrl"), testUrl: value("testUrl"), productionUrl: value("productionUrl"), timeout: value("timeout"), maxRetries: value("maxRetries"), syncMinutes: value("syncMinutes") }, credentials, enabled: form.elements.enabled?.checked || false, endpoints: [...form.querySelectorAll(".connector-endpoint-row")].map(row => ({ id: row.dataset.endpointId, name: row.querySelector("[data-name=endpointName]").value, method: row.querySelector("[data-name=endpointMethod]").value, path: row.querySelector("[data-name=endpointPath]").value, purpose: row.querySelector("[data-name=endpointPurpose]").value, parameters: parseObject(row.querySelector("[data-name=endpointParameters]").value), headers: parseObject(row.querySelector("[data-name=endpointHeaders]").value), body: row.querySelector("[data-name=endpointBody]").value, expectedResponse: row.querySelector("[data-name=endpointExpected]").value })), mappings: [...form.querySelectorAll(".connector-mapping-row")].map(row => ({ apiField: row.querySelector("[data-name=apiField]").value, depannhomeField: row.querySelector("[data-name=depannhomeField]").value, transform: row.querySelector("[data-name=transform]").value })) }; }
function credentialInputs(type) { if (type === "basic") return '<label>Identifiant<input data-credential="username" autocomplete="off"></label><label>Mot de passe<input data-credential="password" type="password" autocomplete="new-password"></label>'; if (type === "custom") return '<label class="form-wide">Headers JSON personnalisés (secret)<textarea data-credential="headers" rows="2" placeholder=\'{"X-Partner-Secret":"…"}\'></textarea></label>'; if (type === "oauth2") return '<label>Access token<input data-credential="accessToken" type="password" autocomplete="new-password"></label>'; return `<label>${type === "apiKey" ? "Clé API" : "Token"}<input data-credential="${type === "apiKey" ? "apiKey" : "token"}" type="password" autocomplete="new-password"></label>${type === "apiKey" ? '<label>Nom du header<input data-credential="headerName" value="X-API-Key"></label>' : ""}`; }
async function toggleConnector(id) { const connector = data.connectors.find(item => Number(item.id) === Number(id)); const result = await api(`/api/connectors/${id}/status`, { method: "PATCH", body: JSON.stringify({ enabled: !connector.enabled }) }); if (!result.ok) return alert(result.message || "Action impossible."); renderConnectors("installed", id); }
async function deleteConnector(id) { if (!confirm("Supprimer définitivement ce connecteur et son journal ?")) return; const result = await api(`/api/connectors/${id}`, { method: "DELETE" }); if (!result.ok) return alert(result.message || "Suppression impossible."); selectedId = 0; renderConnectors("installed"); }
async function importBundle(event) { const file = event.target.files[0]; if (!file) return; try { const bundle = JSON.parse(await file.text()); const result = await api("/api/connectors/import", { method: "POST", body: JSON.stringify(bundle) }); if (!result.ok) return alert(result.message || "Import impossible."); selectedId = result.data.id; renderConnectors("edit", selectedId); } catch { alert("Le fichier de connecteur est invalide."); } }
function selectedConnector() { return data.connectors.find(item => Number(item.id) === Number(selectedId)) || data.connectors[0] || null; }
function authLabel(type) { return ({ apiKey: "Clé API", oauth2: "OAuth 2.0", jwt: "Jeton JWT", basic: "Authentification classique", bearer: "Jeton d’accès", custom: "Authentification personnalisée" })[type] || "Authentification non renseignée"; }
function logStatusLabel(status) { return ({ success: "Réussi", failed: "Échec", pending: "En attente" })[status] || "État non renseigné"; }
function logActionLabel(action) { return ({ created: "Création", updated: "Mise à jour", deleted: "Suppression", imported: "Importation", exported: "Exportation", tested: "Test", enabled: "Activation", disabled: "Désactivation" })[action] || "Opération"; }
function slug(value) { return String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 64); }
function parseObject(value) { try { const parsed = JSON.parse(value || "{}"); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {}; } catch { return {}; } }
function dateTime(value) { return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : ""; }
async function api(url, options = {}) { try { const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const payload = response.status === 204 ? null : await response.json().catch(() => null); return { ok: response.ok, data: payload, message: payload?.message }; } catch { return { ok: false, message: "Serveur indisponible." }; } }
