import { ROUTES } from "./config.js?v=118";
import { clearSearch, getContainer, setPage } from "./ui.js?v=44";
import { escapeHtml } from "./utils.js?v=44";

const SECTIONS = [["cover", "Couverture"], ["overview", "État des lieux"], ["installation", "Installation"], ["visual", "Contrôle visuel"], ["measurements", "Mesures techniques"], ["leakSearch", "Recherche de fuite"], ["location", "Localisation"], ["work", "Travaux réalisés"], ["finalControl", "Contrôle final"], ["conclusion", "Conclusion"], ["signatures", "Signatures"]];
const LEAK_METHODS = ["Manomètre de pression", "Détecteur électronique", "Gaz traceur", "Traceur UV", "Mousse détectrice", "Caméra thermique", "Autre méthode"];
let reports = []; let library = []; let current = null; let corrections = []; let autoSaveTimer = null; let autoSaving = false;

export async function renderTechnicalReports(reportId = 0, appointmentId = 0) {
    clearSearch(); setPage("Rapports de recherche de fuite", ROUTES.technicalReports, "detail");
    const container = getContainer(); container.innerHTML = '<section class="client-panel report-shell"><p class="muted">Chargement des rapports…</p></section>';
    const loaded = await api("/api/technical-reports"); if (!loaded.ok) return renderFailure(container, loaded.message);
    reports = loaded.data.reports || []; library = loaded.data.library || [];
    if (reportId) { const detail = await api(`/api/technical-reports/${reportId}`); if (detail.ok) { current = detail.data.report; corrections = detail.data.corrections || []; } }
    else if (appointmentId) await createFromAppointment(appointmentId, container);
    const shell = container.querySelector(".report-shell");
    if (current) return renderEditor(shell);
    renderDirectory(shell);
}

function renderDirectory(node) {
    node.innerHTML = `<header class="report-heading"><div><p class="eyebrow">Rapports techniques</p><h2>Recherche de fuite</h2><p class="muted">Créez le rapport depuis une intervention, suivez sa validation et archivez le PDF client.</p></div>${isAdmin() ? '<button class="secondary-button" id="reportLibrary">Bibliothèque technique</button>' : ""}</header><section class="report-panel"><div class="form-heading"><div><p class="eyebrow">Interventions</p><h3>Démarrer un rapport</h3></div></div><div id="reportAppointments"><p class="muted">Chargement des interventions récentes…</p></div></section><section class="report-panel"><div class="form-heading"><div><p class="eyebrow">Suivi</p><h3>Rapports existants</h3></div></div><div class="report-list">${reports.length ? reports.map(reportCard).join("") : '<p class="muted">Aucun rapport créé pour le moment.</p>'}</div></section>`;
    node.querySelector("#reportLibrary")?.addEventListener("click", () => renderLibrary(node));
    node.querySelectorAll("[data-open-report]").forEach(button => button.addEventListener("click", () => renderTechnicalReports(button.dataset.openReport)));
    loadAppointments(node.querySelector("#reportAppointments"));
}
function reportCard(report) { return `<article><div><p class="eyebrow">${escapeHtml(report.title)} · ${statusLabel(report.status)}</p><h4>Intervention #${report.appointmentId || "—"}</h4><p class="muted">${escapeHtml(date(report.reportDate))} · ${escapeHtml(report.technicianName || "Technicien")}</p></div><div class="report-card-actions"><button class="secondary-button" data-open-report="${report.id}">Ouvrir</button>${report.status === "validated" ? `<a class="secondary-button" href="/api/technical-reports/${report.id}/pdf" target="_blank">PDF</a>` : ""}</div></article>`; }
async function loadAppointments(node) { const today = new Date(); const start = new Date(today); start.setDate(today.getDate() - 90); const end = new Date(today); end.setDate(today.getDate() + 90); const result = await api(`/api/calendar/events?start=${toDate(start)}&end=${toDate(end)}`); if (!result.ok) { node.innerHTML = `<p class="auth-message error">${escapeHtml(result.message || "Impossible de charger les interventions.")}</p>`; return; } const appointments = (result.data.events || []).filter(event => event.eventType === "appointment"); node.innerHTML = appointments.length ? `<div class="report-appointment-list">${appointments.map(event => { const existing = reports.find(report => Number(report.appointmentId) === Number(event.id)); return `<article><div><strong>${escapeHtml(event.title)}</strong><p>${escapeHtml(event.clientName || "Client non renseigné")} · ${escapeHtml(date(event.date))}</p></div>${existing ? `<button class="secondary-button" data-open-report="${existing.id}">Ouvrir le rapport</button>` : `<button class="secondary-button" data-new-report="${event.id}">Créer le rapport</button>`}</article>`; }).join("")}</div>` : '<p class="muted">Aucune intervention accessible sur cette période.</p>'; node.querySelectorAll("[data-open-report]").forEach(button => button.addEventListener("click", () => renderTechnicalReports(button.dataset.openReport))); node.querySelectorAll("[data-new-report]").forEach(button => button.addEventListener("click", () => renderTechnicalReports(0, button.dataset.newReport))); }
async function createFromAppointment(appointmentId, container) { const result = await api(`/api/technical-reports/appointments/${appointmentId}`); if (!result.ok) { renderFailure(container, result.message); return; } if (result.data.report) { current = result.data.report; corrections = []; return; } const appointment = result.data.appointment; const created = await api("/api/technical-reports", { method: "POST", body: JSON.stringify({ appointmentId, title: "Rapport de recherche de fuite", reportDate: appointment.date, content: defaultContent() }) }); if (!created.ok) { renderFailure(container, created.message); return; } const detail = await api(`/api/technical-reports/${created.data.id}`); if (detail.ok) { current = detail.data.report; corrections = []; } }

function renderEditor(node) {
    const report = current; const editable = report.status !== "validated" && (isAdmin() || Number(report.createdBy) === Number(document.body.dataset.userId));
    node.innerHTML = `<header class="report-heading"><div><button class="report-back secondary-button" id="reportBack">← Rapports</button><p class="eyebrow">Rapport #${report.id} · <span class="report-status ${report.status}">${statusLabel(report.status)}</span></p><h2>${escapeHtml(report.title)}</h2><p class="muted">Sauvegarde automatique active${editable ? "" : " · Document verrouillé"}.</p></div><div class="report-heading-actions">${report.status === "validated" ? `<a class="secondary-button" href="/api/technical-reports/${report.id}/pdf" target="_blank">Ouvrir le PDF</a>` : ""}${editable ? '<button class="secondary-button" id="saveReport">Enregistrer</button>' : ""}</div></header>${corrections.length ? `<section class="report-corrections"><h3>Corrections demandées</h3>${corrections.map(item => `<article><strong>${sectionLabel(item.section)}</strong><p>${escapeHtml(item.comment)}</p><small>${escapeHtml(item.requestedBy || "Administration")} · ${dateTime(item.createdAt)}</small></article>`).join("")}</section>` : ""}<nav class="report-tabs">${SECTIONS.map(([key, label]) => `<button class="secondary-button${key === "cover" ? " active" : ""}" data-report-section="${key}">${label}</button>`).join("")}</nav><section id="reportEditorContent"></section><footer class="report-actions" id="reportActions"></footer>`;
    node.querySelector("#reportBack").addEventListener("click", () => { current = null; renderTechnicalReports(); }); node.querySelector("#saveReport")?.addEventListener("click", () => saveReport(node));
    node.querySelectorAll("[data-report-section]").forEach(button => button.addEventListener("click", () => openSection(node, button.dataset.reportSection)));
    openSection(node, "cover"); renderActions(node, editable);
}
function openSection(shell, key) { shell.querySelectorAll("[data-report-section]").forEach(button => button.classList.toggle("active", button.dataset.reportSection === key)); const node = shell.querySelector("#reportEditorContent"); node.innerHTML = sectionHtml(key); bindSection(node, key, shell); }
function sectionHtml(key) { const content = current.content; const media = (current.media || []).filter(item => item.section === key); const fields = (items) => `<div class="form-grid">${items.map(([name, label, type = "text"]) => `<label>${label}<${type === "textarea" ? "textarea rows=\"3\"" : `input type=\"${type}\"`} name="${name}" value="${type === "textarea" ? "" : escapeHtml(content[key][name] || "")}">${type === "textarea" ? escapeHtml(content[key][name] || "") + "</textarea>" : ""}</label>`).join("")}</div>`;
    const mediaHtml = `<section class="report-media"><div class="form-heading"><div><p class="eyebrow">Photos de la section</p><h3>Photos, légendes et annotations</h3></div><label class="secondary-button">Ajouter des photos<input data-media-input type="file" accept="image/*" capture="environment" multiple></label></div><label>Légende commune<input id="mediaCaption" maxlength="500"></label><label>Annotation / repère<input id="mediaAnnotation" maxlength="1000" placeholder="Ex. Fuite localisée à gauche du raccord"></label><div class="report-media-grid">${media.map(item => `<article><img src="${escapeHtml(item.dataUrl)}" alt="${escapeHtml(item.caption || item.name)}"><input data-caption="${item.id}" value="${escapeHtml(item.caption || "")}" placeholder="Légende"><input data-annotation="${item.id}" value="${escapeHtml(item.annotation || "")}" placeholder="Annotation"><button class="danger-button" data-delete-media="${item.id}">Supprimer</button></article>`).join("") || '<p class="muted">Aucune photo dans cette section.</p>'}</div></section>`;
    if (key === "cover") return `<section class="report-panel"><h3>Couverture</h3>${fields([["insurance", "Assurance"], ["claimNumber", "Numéro de dossier"], ["interventionReference", "Référence intervention"]])}<label>Photo générale utilisée en couverture<select name="generalPhotoId"><option value="">Première photo de couverture</option>${(current.media || []).filter(item => item.section === "cover").map(item => `<option value="${item.id}" ${content.cover.generalPhotoId === item.id ? "selected" : ""}>${escapeHtml(item.caption || item.name)}</option>`).join("")}</select></label>${mediaHtml}</section>`;
    if (key === "overview") return `<section class="report-panel"><h3>État des lieux</h3>${fields([["generalDescription", "Description générale", "textarea"], ["incidentNature", "Nature du sinistre", "textarea"], ["customerHistory", "Historique communiqué", "textarea"], ["context", "Contexte", "textarea"], ["interventionConditions", "Conditions d’intervention", "textarea"]])}${mediaHtml}</section>`;
    if (key === "installation") return `<section class="report-panel"><h3>Description de l’installation</h3>${fields([["installationType", "Type d’installation"], ["brand", "Marque"], ["model", "Modèle"], ["year", "Année"], ["refrigerant", "Fluide frigorigène"], ["serialNumber", "Numéro de série"], ["power", "Puissance"]])}${mediaHtml}</section>`;
    if (key === "visual") return checklistHtml(key, "Contrôle visuel", content.visual, mediaHtml);
    if (key === "measurements" || key === "finalControl") return measuresHtml(key, key === "measurements" ? "Mesures techniques" : "Contrôle final", content[key], mediaHtml);
    if (key === "leakSearch") return leakHtml(mediaHtml);
    if (key === "location") return `<section class="report-panel"><h3>Localisation de la fuite</h3>${fields([["description", "Description précise", "textarea"], ["preciseLocation", "Localisation", "textarea"], ["comments", "Commentaires", "textarea"]])}${mediaHtml}</section>`;
    if (key === "work") return `<section class="report-panel"><h3>Travaux réalisés</h3>${fields([["repair", "Réparation", "textarea"], ["replacement", "Remplacement", "textarea"], ["recharge", "Recharge", "textarea"], ["refrigerantQuantity", "Quantité de fluide"], ["tests", "Essais réalisés", "textarea"], ["equipment", "Matériel utilisé", "textarea"]])}${mediaHtml}</section>`;
    if (key === "conclusion") return `<section class="report-panel"><h3>Conclusion</h3>${fields([["recommendations", "Préconisations", "textarea"]])}${libraryInsert("conclusion")}${mediaHtml}</section>`;
    return `<section class="report-panel"><h3>Signatures</h3><div class="form-grid"><label>Nom du client signataire<input name="clientName" value="${escapeHtml(content.signatures.clientName || "")}"></label><label>Date de signature<input name="signedAt" type="date" value="${escapeHtml(content.signatures.signedAt || "")}"></label></div><div class="report-signatures"><label>Signature technicien<canvas data-signature="technician" width="640" height="220"></canvas><button class="secondary-button" data-clear-signature="technician">Effacer</button></label><label>Signature client<canvas data-signature="client" width="640" height="220"></canvas><button class="secondary-button" data-clear-signature="client">Effacer</button></label></div></section>`;
}
function checklistHtml(key, title, data, media) { return `<section class="report-panel"><h3>${title}</h3><div id="checkRows">${(data.checklist || []).map((item, index) => `<div class="report-row"><input data-check-label value="${escapeHtml(item.label || "")}" placeholder="Point de contrôle"><label><input data-check-state type="checkbox" ${item.checked ? "checked" : ""}> Conforme</label><button class="danger-button" data-remove-row="${index}">×</button></div>`).join("")}</div><button class="secondary-button" data-add-check>Ajouter un contrôle</button><label>Observations<textarea name="observations" rows="3">${escapeHtml(data.observations || "")}</textarea></label><label>Anomalies constatées<textarea name="anomalies" rows="3">${escapeHtml(data.anomalies || "")}</textarea></label>${media}</section>`; }
function measuresHtml(key, title, data, media) { const extras = key === "finalControl" ? `<label>Contrôle d’étanchéité<textarea name="tightness">${escapeHtml(data.tightness || "")}</textarea></label><label>Essais de fonctionnement<textarea name="operatingTests">${escapeHtml(data.operatingTests || "")}</textarea></label><label>Validation<textarea name="validation">${escapeHtml(data.validation || "")}</textarea></label>` : ""; return `<section class="report-panel"><h3>${title}</h3><div id="measureRows">${(data.rows || []).map((row, index) => measureRow(row, index)).join("")}</div><button class="secondary-button" data-add-measure>Ajouter une mesure</button>${extras}${media}</section>`; }
function measureRow(row, index) { return `<div class="report-row"><input data-measure-label value="${escapeHtml(row.label || "")}" placeholder="Ex. Pression HP"><input data-measure-value value="${escapeHtml(row.value || "")}" placeholder="Valeur"><input data-measure-unit value="${escapeHtml(row.unit || "")}" placeholder="Unité"><button class="danger-button" data-remove-row="${index}">×</button></div>`; }
function leakHtml(media) { const methods = current.content.leakSearch.methods || []; return `<section class="report-panel"><h3>Recherche de fuite</h3><div id="methodRows">${methods.map((item, index) => methodRow(item, index)).join("")}</div><button class="secondary-button" data-add-method>Ajouter une méthode</button>${media}</section>`; }
function methodRow(item, index) { return `<article class="report-method"><select data-method-name>${LEAK_METHODS.map(name => `<option ${item.name === name ? "selected" : ""}>${name}</option>`).join("")}</select><label>Résultat<input data-method-result value="${escapeHtml(item.result || "")}"></label><label>Observations<textarea data-method-observations>${escapeHtml(item.observations || "")}</textarea></label><label>Commentaires<textarea data-method-comments>${escapeHtml(item.comments || "")}</textarea></label><button class="danger-button" data-remove-row="${index}">Retirer</button></article>`; }
function libraryInsert(category) { const items = library.filter(item => item.category === category || item.category === "phrases"); return items.length ? `<label>Bibliothèque<select data-library-insert><option value="">Insérer un contenu…</option>${items.map(item => `<option value="${item.id}">${escapeHtml(item.label)}</option>`).join("")}</select></label>` : ""; }
function bindSection(node, key, shell) { const editable = current.status !== "validated" && (isAdmin() || Number(current.createdBy) === Number(document.body.dataset.userId)); node.querySelectorAll("input, textarea, select").forEach(input => { input.disabled = !editable; input.addEventListener("input", () => queueAutoSave(shell)); input.addEventListener("change", () => queueAutoSave(shell)); }); node.querySelector("[data-add-check]")?.addEventListener("click", () => { current.content.visual.checklist.push({ label: "", checked: false }); openSection(shell, key); }); node.querySelector("[data-add-measure]")?.addEventListener("click", () => { current.content[key].rows.push({ label: "", value: "", unit: "" }); openSection(shell, key); }); node.querySelector("[data-add-method]")?.addEventListener("click", () => { current.content.leakSearch.methods.push({ name: LEAK_METHODS[0], result: "", observations: "", comments: "" }); openSection(shell, key); }); node.querySelectorAll("[data-remove-row]").forEach(button => button.addEventListener("click", () => { const index = Number(button.dataset.removeRow); if (key === "visual") current.content.visual.checklist.splice(index, 1); else if (["measurements", "finalControl"].includes(key)) current.content[key].rows.splice(index, 1); else current.content.leakSearch.methods.splice(index, 1); openSection(shell, key); })); node.querySelector("[data-library-insert]")?.addEventListener("change", event => { const item = library.find(candidate => String(candidate.id) === event.target.value); if (item) { const field = node.querySelector("textarea[name=recommendations]"); if (field) { field.value = [field.value, item.content.text || item.label].filter(Boolean).join("\n"); queueAutoSave(shell); } } }); bindMedia(node, key, shell, editable); bindSignatures(node, shell, editable); }
function collectSection(node, key) { const value = current.content[key]; const get = name => node.querySelector(`[name="${name}"]`)?.value ?? value[name]; if (key === "visual") value.checklist = [...node.querySelectorAll(".report-row")].map(row => ({ label: row.querySelector("[data-check-label]").value, checked: row.querySelector("[data-check-state]").checked })); if (["measurements", "finalControl"].includes(key)) value.rows = [...node.querySelectorAll(".report-row")].map(row => ({ label: row.querySelector("[data-measure-label]").value, value: row.querySelector("[data-measure-value]").value, unit: row.querySelector("[data-measure-unit]").value })); if (key === "leakSearch") value.methods = [...node.querySelectorAll(".report-method")].map(row => ({ name: row.querySelector("[data-method-name]").value, result: row.querySelector("[data-method-result]").value, observations: row.querySelector("[data-method-observations]").value, comments: row.querySelector("[data-method-comments]").value })); Object.keys(value).forEach(name => { const input = node.querySelector(`[name="${name}"]`); if (input) value[name] = input.value; }); }
function queueAutoSave(shell) { const section = shell.querySelector("[data-report-section].active")?.dataset.reportSection; if (section) collectSection(shell.querySelector("#reportEditorContent"), section); clearTimeout(autoSaveTimer); autoSaveTimer = setTimeout(() => saveReport(shell, true), 700); }
async function saveReport(shell, silent = false) { if (autoSaving) return; const section = shell.querySelector("[data-report-section].active")?.dataset.reportSection; if (section) collectSection(shell.querySelector("#reportEditorContent"), section); autoSaving = true; const result = await api(`/api/technical-reports/${current.id}`, { method: "PUT", body: JSON.stringify({ appointmentId: current.appointmentId, clientId: current.clientId, title: current.title, reportDate: current.reportDate, content: current.content }) }); autoSaving = false; const status = shell.querySelector(".report-heading .muted"); if (!result.ok) { if (!silent) alert(result.message || "Enregistrement impossible."); return; } if (status) status.textContent = `Enregistré automatiquement à ${new Intl.DateTimeFormat("fr-FR", { timeStyle: "short" }).format(new Date())}.`; }
function bindMedia(node, section, shell, editable) { const input = node.querySelector("[data-media-input]"); if (input) input.disabled = !editable; input?.addEventListener("change", async () => { const files = [...input.files]; if (!files.length) return; const form = new FormData(); files.forEach(file => form.append("files", file)); form.append("section", section); form.append("caption", node.querySelector("#mediaCaption")?.value || ""); form.append("annotation", node.querySelector("#mediaAnnotation")?.value || ""); const result = await upload(`/api/technical-reports/${current.id}/media`, form); if (!result.ok) return alert(result.message || "Ajout des photos impossible."); current.media.push(...result.data.media); openSection(shell, section); }); node.querySelectorAll("[data-caption], [data-annotation]").forEach(input => input.addEventListener("change", async () => { const id = input.dataset.caption || input.dataset.annotation; const item = current.media.find(media => media.id === id); const card = input.closest("article"); item.caption = card.querySelector("[data-caption]").value; item.annotation = card.querySelector("[data-annotation]").value; await api(`/api/technical-reports/${current.id}/media/${id}`, { method: "PATCH", body: JSON.stringify({ caption: item.caption, annotation: item.annotation }) }); })); node.querySelectorAll("[data-delete-media]").forEach(button => button.addEventListener("click", async () => { if (!confirm("Supprimer cette photo ?")) return; const result = await api(`/api/technical-reports/${current.id}/media/${button.dataset.deleteMedia}`, { method: "DELETE" }); if (result.ok) { current.media = current.media.filter(item => item.id !== button.dataset.deleteMedia); openSection(shell, section); } })); }
function bindSignatures(node, shell, editable) { node.querySelectorAll("canvas[data-signature]").forEach(canvas => { const name = canvas.dataset.signature; const signature = signatureCanvas(canvas, current.content.signatures[name], editable); node.querySelector(`[data-clear-signature="${name}"]`)?.addEventListener("click", () => { signature.clear(); current.content.signatures[name] = ""; queueAutoSave(shell); }); signature.onEnd(() => { current.content.signatures[name] = signature.value(); queueAutoSave(shell); }); }); }
function signatureCanvas(canvas, source, editable) { const context = canvas.getContext("2d"); context.strokeStyle = "#003b73"; context.lineWidth = 3; context.lineCap = "round"; let drawing = false, marked = false, ended = () => {}; const point = event => { const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; }; const load = () => { if (!source) return; const image = new Image(); image.onload = () => { context.drawImage(image, 0, 0, canvas.width, canvas.height); marked = true; }; image.src = source; }; canvas.addEventListener("pointerdown", event => { if (!editable) return; drawing = true; canvas.setPointerCapture(event.pointerId); const p = point(event); context.beginPath(); context.moveTo(p.x, p.y); }); canvas.addEventListener("pointermove", event => { if (!drawing) return; const p = point(event); context.lineTo(p.x, p.y); context.stroke(); marked = true; }); ["pointerup", "pointercancel"].forEach(type => canvas.addEventListener(type, () => { if (drawing) ended(); drawing = false; })); load(); return { clear: () => { context.clearRect(0, 0, canvas.width, canvas.height); marked = false; }, value: () => marked ? canvas.toDataURL("image/png") : "", onEnd: callback => { ended = callback; } }; }
function renderActions(shell, editable) { const node = shell.querySelector("#reportActions"); const bindReopen = () => node.querySelector("#reopenReport")?.addEventListener("click", async () => { if (!confirm("Remettre ce rapport en brouillon ?")) return; const result = await api(`/api/technical-reports/${current.id}/reopen`, { method: "POST" }); if (result.ok) renderTechnicalReports(current.id); }); if (!editable) { if (isAdmin() && current.status === "validated") node.innerHTML = '<button class="secondary-button" id="reopenReport">Remettre en brouillon</button>'; bindReopen(); return; } node.innerHTML = `${current.status !== "submitted" ? '<button class="secondary-button" id="submitReport">Envoyer à validation</button>' : ""}${isAdmin() && current.status === "submitted" ? '<button class="secondary-button" id="validateReport">Valider et archiver le PDF</button>' : ""}${isAdmin() && current.status !== "draft" ? '<button class="secondary-button" id="reopenReport">Remettre en brouillon</button>' : ""}${isAdmin() ? `<form id="correctionForm"><select name="section">${SECTIONS.map(([key, label]) => `<option value="${key}">${label}</option>`).join("")}</select><input name="comment" required maxlength="2000" placeholder="Demander une correction ciblée"><button class="secondary-button">Demander une correction</button></form>` : ""}`; bindReopen(); node.querySelector("#submitReport")?.addEventListener("click", async () => { await saveReport(shell); const result = await api(`/api/technical-reports/${current.id}/submit`, { method: "POST" }); if (!result.ok) return alert(result.message || "Envoi impossible."); renderTechnicalReports(current.id); }); node.querySelector("#validateReport")?.addEventListener("click", async () => { if (!confirm("Valider ce rapport, générer puis archiver le PDF ?")) return; const result = await api(`/api/technical-reports/${current.id}/validate`, { method: "POST" }); if (!result.ok) return alert(result.message || "Validation impossible."); renderTechnicalReports(current.id); }); node.querySelector("#correctionForm")?.addEventListener("submit", async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const result = await api(`/api/technical-reports/${current.id}/corrections`, { method: "POST", body: JSON.stringify(values) }); if (!result.ok) return alert(result.message || "Demande impossible."); renderTechnicalReports(current.id); }); }
function renderLibrary(node) { node.innerHTML = `<section class="report-panel"><button class="secondary-button" id="backReports">← Retour</button><h3>Bibliothèque technique</h3><form id="libraryForm" class="form-grid"><label>Catégorie<select name="category"><option value="phrases">Phrase technique</option><option value="conclusion">Conclusion / recommandation</option><option value="checklist">Check-list</option><option value="measurements">Tableau préconfiguré</option></select></label><label>Libellé<input name="label" required maxlength="160"></label><label class="form-wide">Contenu<textarea name="text" rows="3"></textarea></label><button class="secondary-button">Ajouter</button></form><div class="report-library-list">${library.map(item => `<article><div><strong>${escapeHtml(item.label)}</strong><p>${escapeHtml(item.category)}</p></div><button class="danger-button" data-delete-library="${item.id}">Supprimer</button></article>`).join("") || '<p class="muted">Aucun contenu personnalisé.</p>'}</div></section>`; node.querySelector("#backReports").addEventListener("click", () => renderTechnicalReports()); node.querySelector("#libraryForm").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await api("/api/technical-reports/library", { method: "POST", body: JSON.stringify({ category: form.get("category"), label: form.get("label"), content: { text: form.get("text") } }) }); if (result.ok) renderTechnicalReports(); else alert(result.message || "Ajout impossible."); }); node.querySelectorAll("[data-delete-library]").forEach(button => button.addEventListener("click", async () => { if (!confirm("Supprimer cet élément ?")) return; await api(`/api/technical-reports/library/${button.dataset.deleteLibrary}`, { method: "DELETE" }); renderTechnicalReports(); })); }
function defaultContent() { return { cover: { insurance: "", claimNumber: "", interventionReference: "", generalPhotoId: "" }, overview: { generalDescription: "", incidentNature: "", customerHistory: "", context: "", interventionConditions: "" }, installation: { installationType: "", brand: "", model: "", year: "", refrigerant: "", serialNumber: "", power: "" }, visual: { checklist: [], observations: "", anomalies: "" }, measurements: { rows: defaultMeasures() }, leakSearch: { methods: [] }, location: { description: "", preciseLocation: "", comments: "" }, work: { repair: "", replacement: "", recharge: "", refrigerantQuantity: "", tests: "", equipment: "" }, finalControl: { rows: defaultMeasures(), tightness: "", operatingTests: "", validation: "" }, conclusion: { recommendations: "" }, signatures: { technician: "", client: "", clientName: "", signedAt: "" } }; }
function defaultMeasures() { return ["Pression HP", "Pression BP", "Température aspiration", "Température refoulement", "Température extérieure", "Température intérieure", "Intensité", "Tension", "Débit"].map(label => ({ label, value: "", unit: "" })); }
function sectionLabel(key) { return SECTIONS.find(([id]) => id === key)?.[1] || key; } function statusLabel(status) { return ({ draft: "Brouillon", submitted: "Soumis", in_correction: "Corrections demandées", validated: "Validé" })[status] || status; } function isAdmin() { return document.body.dataset.role === "admin"; } function toDate(value) { return value.toISOString().slice(0, 10); } function date(value) { return value ? new Intl.DateTimeFormat("fr-FR").format(new Date(`${value}T12:00:00`)) : ""; } function dateTime(value) { return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : ""; } function renderFailure(node, message) { node.innerHTML = `<section class="client-panel"><p class="auth-message error">${escapeHtml(message || "Impossible de charger les rapports.")}</p></section>`; }
async function api(url, options = {}) { try { const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => null); return { ok: response.ok, data, message: data?.message }; } catch { return { ok: false, message: "Serveur indisponible." }; } } async function upload(url, body) { try { const response = await fetch(url, { method: "POST", credentials: "same-origin", body }); const data = await response.json().catch(() => null); return { ok: response.ok, data, message: data?.message }; } catch { return { ok: false, message: "Serveur indisponible." }; } }
